apis.md

Fixes a minor misspelling and a grammar issue.

Fix minor typos

---

_config.yml

(already added the CNAME file to master... seems to work)

save some redirects

---

_config.yml
apis.md
implementors.md
spec.md

... and some other things.
Highly recommend clicking this button: 
Open to nits on presentation / organization... I would ask that concerns about the actual semantics themselves be opened as github issues proper, though.
Thanks!

language-independent semantics documentation

---

_config.yml
apis.md
index.md

Sync page names with references to them, and fix repository names on the API page

---

use-cases.md

@adriancole addresses some of your comments.

Clarify two context propagation techniques; address some comments.

---

spec.md

per https://github.com/opentracing/opentracing-go/pull/39 and https://github.com/opentracing/opentracing-python/pull/11 ...

update copy about log messages

---

Gemfile
_config.yml
use-cases.md

Per #49 and #53's semi-failure...

make rouge work

---

use-cases.md

users vs implementors copy

---

spec.md
use-cases.md

(per https://github.com/opentracing/opentracing.github.io/issues/44, https://github.com/opentracing/opentracing-go/pull/48, and https://github.com/opentracing/opentracing-go/pull/50)

update the docs to match the latest thinking

---

_includes/sidebar.html
index.md

Fixes display/scaling issue shown in https://github.com/opentracing/opentracing.github.io/pull/62

Move tag line from sidebar to home page

---

spec.md

Per https://github.com/opentracing/opentracing-java/pull/9#discussion_r54152216

Add a better description of log "events"

---

spec.md
use-cases.md

Per https://github.com/opentracing/opentracing.github.io/issues/70

Remove the Injector/Extractor layer in the spec

---

spec.md

Per discussion in https://github.com/opentracing/opentracing.github.io/issues/73
I will start working on .py and .go changes later today.

Move to simpler required carriers

---

_config.yml
propagation.md
spec.md

Most of the writing is new, though some was moved from `spec.md`.

Add more detailed notes about Inject and Join

---

spec.md

See https://github.com/opentracing/opentracing.github.io/pull/80 
Closes #27

Adopt @beberlei's documentation change

---

index.md

The previous link didn't exist, I think that you wanted to link to integrations.

Update broken link

---

data-semantics.md
propagation.md
spec.md
use-cases.md

Per https://github.com/opentracing/opentracing.github.io/issues/99 and https://github.com/opentracing/opentracing-go/pull/82 .

Introduce SpanContext, s/Join/Extract/, etc

---

spec.md

Clarify best practices for operation names

---

_posts/2016-07-20-weekly-hangout.md

For your review @bensigelman . Needs some edits!

Create notes for 2016-07-20 meeting

---

data-semantics.md

Document sampling.priority tag

---

spec.md

Per https://github.com/opentracing/opentracing.github.io/issues/106

Update spec per SpanContext/Span/Baggage changes

---

_data/tracers.yaml

Add Jaeger as "supported tracer"

---

_docs/pages/authors-and-contributors.md

send this rp again, same with #159, only one commit log. :) 
@bensigelman @yurishkuro

add myself as a contributor

---

_docs/pages/api/data-conventions.md
_docs/pages/quick-start.md
_docs/pages/spec.md

Fixes #161 
Relevant to https://github.com/opentracing/specification/issues/12, https://github.com/opentracing/specification/issues/13, and https://github.com/opentracing/specification/issues/16

modernize specification doc

---

_docs/pages/supported-tracers.md

@bensigelman as discussed previously

Separate Zipkin and Jaeger descriptions

---

_docs/pages/api/data-conventions.md

Noticed this while reading through the docs so I thought I'd open a PR.

Fixed a typo

---

_includes/header.html

@yurishkuro @bensigelman What do you think about this? I think it would be good to have a link to the contrib organization in menu too.

Header link to contrib organization

---

_layouts/default.html

add custom google analytics event for

---

_docs/pages/spec.md

(really this is just an attempt to re-kick-off TravisCI which had an S3-related blip earlier)

Adjust wording

---

_data/frameworks.yaml
img/frameworks/hprose.svg

Finally released. And here is the snapshot:

Add hprose in supported frameworks.

---

_data/links.yaml
_sass/_components/_header.scss

- fix issue where FAQ was added then removed.
- fix issue when header right section takes up to much space on safari

fixes #195

---

_talks_and_videos/2017-03-28-opentracing-project-update.md
_talks_and_videos/2017-03-29-01-opentracing-isnt-just-tracing.md
_talks_and_videos/2017-03-29-02-loki.md
_talks_and_videos/2017-03-29-03-operational-and-business-insights.md
_talks_and_videos/2017-03-29-04-opentracing-and-containers.md

New thumbnails look awesome though! Also added new keynote video

Old links broke due KubeCon/NativeCloudCon replaced videos. 

---

_docs/pages/quick-start.md

Defer in separate functions

---

_data/language.yaml
_includes/hero.html

Add ruby and csharp to index page

---

_data/language.yaml
_docs/pages/api/api-implementations.md
_includes/hero.html

Adding the new php API to the list.

List PHP as a supported language

---

.travis.yml
_docs/pages/instrumentation/common-use-cases.md

Fix typo in docs

---

pages/outreachy.md

Signed-off-by: Gary Brown <gary@brownuk.com>

Further refinement of the outreachy landing page

---

pages/outreachy.md

Outreachy - Added issues suitable for small contributions

---

pages/outreachy.md

Updated the deadline for Outreachy

---

_docs/pages/supported-tracers.md

Hi there,
We wrote an opentracing implementation at my employer.
Although it has some limitations I thought it might be of interest for some devs.

Add javascript opentracing implementation

---

CONTRIBUTING.md

@tedsuo had a valid point of it being unclear how we deploy changes once a PR is merged so here is a short description for future contributors. :)

Add deploy description

---

_docs/pages/quick-start.md

Add https://github.com/yurishkuro/opentracing-tutorial

---

_docs/pages/supported-tracers.md

Update Jaeger link and description

---

pages/outreachy-201702.md
pages/outreachy.md

Updated Outreachy page for the new program

---

_includes/hero.html

update link to outreachy medium blog post

---

_includes/hero.html

PTAL @yurishkuro @tedsuo (just in case)

Update homepage to announce february newsletter

---

CONTRIBUTING.md

- Add nvm --version command to CONTRIBUTING.md for version check

Add nvm command to check its version in CONTRIBUTING.md

---

.gitignore
content/documentation/_index.md
content/documentation/api.md
content/documentation/authors-and-contributors.md
content/documentation/instrumentation/instrumenting-frameworks.md
content/documentation/instrumentation/practices.md
content/documentation/quick-start.md
content/documentation/spec.md
content/documentation/supported-tracers.md
content/documentation/translations.md
data/links.yaml
themes/tracer/layouts/partials/home/why.html

- Fixes all broken links
- Adding new pages with some dummy content

Adding pages to "404: Page not found" links

---

content/get-involved/_index.md
content/get-involved/contrib.md
content/get-involved/create-a-rfc.md
content/get-involved/join-a-working-group.md
content/get-involved/register.md
content/get-involved/rfc.md
content/get-involved/working-group.md
content/guides/javascript/intro.md
data/links.yaml
get-involved/create-a-rfc.md
get-involved/involve.md
get-involved/join-a-working-group.md
get-involved/join-ot-contrib.md
get-involved/register-your-project.md
themes/tracer/layouts/get-involved/list.html
themes/tracer/layouts/get-involved/single.html
themes/tracer/layouts/partials/header.html

- Fixes some broken links
- Adding sidebar nav for "Get Involved" section

Adding sidebar nav for "Get Involved"

---

content/get-involved/rfc.md
get-involved/create-a-rfc.md
get-involved/involve.md
get-involved/join-a-working-group.md
get-involved/join-ot-contrib.md

- refs #287 
- Provides framework for other pages in "Get Involved" section

Filling in "Join a working group" section of v2.0

---

content/docs/overview/what-is-tracing.md
content/docs/supported-languages.md
data/links.yaml

Updated OpenTracing overview topic.  Changed Overview to be first in the main menu.

Updated OpenTracing overview topic. 

---

content/docs/getting-started/katacoda.md
content/docs/getting-started/tutorials.md

Changed file name from Katacoda to Tutorials (in case people don't know about Katacoda yet).  Added links to language specific tutorials, Hot ROD and Microdounts tutorials.

Adding links to tutorials.

---

content/guides/java/scopes.md

Add content for Java's Scopes.

---

content/docs/overview/spans.md
content/docs/overview/tags-logs-baggage.md

added spans and tags/logs/bags to overview

---

content/docs/faq.md

Not sure if this is enough to close Issue #285 or not?

Created a first draft of an FAQ.

---

content/guides/java/spans.md

Adding documentation for Java:Spans

---

content/guides/python/tracers.md

Add Python: Tracer docs

---

content/docs/overview/scopes-and-threading.md
content/guides/python/spans.md
content/guides/python/tracers.md

Add docs for Python:Spans

---

content/docs/overview/tracers.md

Remove redundant tracing systems list

---

pages/outreachy-201801.md
pages/outreachy.md

Add Outreachy program 2018/2

---

themes/tracer/layouts/registry/single.html

Adds content block for the single registry item template.

Registry pages should support content

---

README.md
content/registry/cpp-jaeger-tracer.md
content/registry/csharp-jaeger-tracer.md
content/registry/go-jaeger-tracer.md
content/registry/java-jaeger-tracer.md
content/registry/nodejs-jaeger-tracer.md
content/registry/python-jaeger-tracer.md

Signed-off-by: Yuri Shkuro <ys@uber.com>

Add Jaeger tracers

---

content/get-involved/register.md

update email on register page to point to our google group (fixes #358)

Update email address

---

content/registry/opentracing-go-redis.md

Fix: https://github.com/smacker/opentracing-go-redis/issues/1

add opentracing-go-redis

---

content/registry/java-jfr-tracer.md

Adding deep tracing capabilities using the JDK Flight Recorder: http://hirt.se/blog/?p=1081.

Add java-jfr-tracer to the registry

---

content/registry/csharp-mongo.md

OpenTracing instrumentation for C# mongodb driver

Adding csharp mongo driver instrumentation

---

content/registry/java-reactor.md

Contribute java-reactor instrumentation library

Add java-reactor

---

content/registry/java-grizzly-ahc.md

Contribute java-grizzly-ahc instrumentation library

Add java-grizzly-ahc

---

content/registry/java-grizzly-http-server.md

Contribute java-grizzly-http-server instrumentation library

Add java-grizzly-http-server

---

content/registry/python-pymongo.md

Includes registry entry for https://github.com/opentracing-contrib/python-pymongo

Add PyMongo instrumentation

---

content/registry/appdash.md
content/registry/dd-trace-dotnet.md
content/registry/dd-trace-go.md
content/registry/dd-trace-java.md
content/registry/dd-trace-js.md
content/registry/dd-trace-php.md
content/registry/dd-trace-py.md
content/registry/dd-trace-rb.md
content/registry/feign-opentracing.md
content/registry/hawkular-apm-opentracing-javascript.md
content/registry/inspectit.md
content/registry/instana-crystal-sensor.md
content/registry/instana-go-sensor.md
content/registry/instana-java-opentracing.md
content/registry/instana-nodejs-sensor.md
content/registry/instana-php-opentracing.md
content/registry/instana-python-sensor.md
content/registry/instana-ruby-sensor.md
content/registry/javascript-opentracing-auto.md
content/registry/koa-opentracing.md
content/registry/opentracing-httpcomponents.md
content/registry/opentracing-jdbc.md
content/registry/opentracing-playframework.md
content/registry/ruby-activerecord-opentracing.md
content/registry/skywalking.md
content/registry/stagemonitor.md
content/registry/test-ruby-opentracing.md
content/registry/zipkin-javascript-opentracing.md

Fixes #403 
See https://github.com/opentracing-contrib/meta/pull/49

Add Meta Contributions to Registry

---

content/registry/python-cassandra.md

Addes cassandra-driver instrumentation to the registry.

Created python-cassandra.md

---

content/docs/overview/tags-logs-baggage.md

Puts emphasis that logs are timed when compared to tags
@yurishkuro let me know if this makes sense

Clarifies overview tags vs logs

---

content/docs/getting-started/_index.md

Fix Java Getting Started

---

content/registry/python-asyncpg.md

Opentracing instrumentation for asyncpg https://github.com/magicStack/asyncpg library

Add Python Asyncpg intstrumentation

---

content/guides/python/inject-extract.md

Updated the TEXT_MAP example

---

content/docs/overview/tracers.md

Typo 2: `no-nop` -> `no-op`

---

.gitignore
README.md
themes/tracer/layouts/partials/css.html
themes/tracer/layouts/partials/home/cncf.html
themes/tracer/layouts/partials/otel.html

- This PR updates the website homepage and the repo README.
- Closes #457
/cc @austinlparker @yurishkuro @tedsuo @caniszczyk
Preview: https://deploy-preview-461--opentracing.netlify.app/

Update project status, banner, and link to migration guide
