opentracing/opentracing.io

- Gemfile
... this also makes the `README.md` work as advertised: https://github.com/opentracing/opentracing.github.io/blame/master/README.md#L16
> add a Gemfile that makes it easy to run jekyll locally

- spec.md
Small proposed addition to explicitly clarify why a TraceContext codec is required in the standard.  
It calls out the obvious-in-retrospect case of needing to keep middleware generic that I hadn't been considering when initially trying to reason why the codec wasn't an implementation detail!
> Add clarifying use case for why the TraceContext codec is part of the standard

- index.md
> Sync tagline wording with home page, emphasize "vendor-neutral"

- spec.md
- use-cases.md
Per https://github.com/opentracing/opentracing-go/pull/40 and https://github.com/opentracing/opentracing.github.io/issues/24
I'll add a few comments inline.
This and https://github.com/opentracing/opentracing-go/pull/40 should have a shared fate.
> remove TraceContext from the docs, too

- _config.yml
- apis.md
- contributors.md
@yurishkuro per https://github.com/opentracing/opentracing.github.io/issues/49, the site mostly "works". The only meaningful regression is that code blocks don't do syntax highlighting. If you read to the bottom at https://github.com/jekyll/jekyll/issues/2709, one does not get the sense that there will be a fix anytime soon. And it seems like we'll have to migrate over, so why not now? (??) Or something.
The rest of the changes are just minor things I noticed while perusing the various pages looking for formatting glitches.
> use kramdown and update some misc things along the way

- spec.md
- use-cases.md
Simplify Span's logging methods to just "log"
Reference: https://github.com/opentracing/opentracing-java/pull/9
> Simplify Span's logging methods to just "log"

- _config.yml
- _includes/sidebar.html
- apis.md
- public/css/syntax.css
> Subdivide the navbar and add info about v1.0RC

- implementors.md
Very low-priority, minor pull request that updates the "Implementing the OpenTracing APIs" page text a bit.  The changes are:
**Split the text into two sections with headings.** The rationale here was I initially clicked on the link to find information *how* to implement the OpenTracing APIs -- but then found text on *why* it's a good idea to do so. Both pieces of information are good and necessary, but I think the headings help as people may come to the page primarily for one purpose or the other.
**Directly include a link to the GitHub repo.** I assume this is the de-facto place to get information on the reference implementations :)
...and also I added some word-smithing that I think makes the content a little more clear (hopefully the improvement here isn't entirely subjective!).
> Minor update to implementors.md

- spec.md
- use-cases.md
C.f. https://github.com/opentracing/opentracing.github.io/issues/67:
"Baggage" is the *set* of Baggage items; so
"Trace Attribute" == "Baggage Item"
and
"Trace Attributes" == "Baggage"
> Use the term Baggage in place of Trace Attributes

- use-cases.md
`and one o them is the so-called "sampling priority"` -> `and one of them is the so-called "sampling priority"`
> Fix typo on use_cases page

- _docs/scripts/linkedHeadings.js
- book.json
We often want to link to specific sections in the spec, but cannot do this easily because the headings aren't linked as anchors.
For example, we can go to http://opentracing.io/documentation/pages/spec#spans directly, but discovering this link exists is not straightforward.  I'd expect to click on this heading to change the url to one including the anchor id.
http://screencast.com/t/hL6HchXXO
Rather than edit every occurrence of h2 and h3 tags, the approach taken in this change is to simply auto-wrap these in anchor tags via javascript.  This will apply to all h2 or h3 tags, regardless of page.
http://screencast.com/t/UlCpHo5TM
> linkedHeadings: linked headings to ids

- _docs/README.MD
- _docs/pages/spec.md
In Tags section, ref of `Data Conventions Guidelines` is error, can't link to the page
> Data Conventions Guidelines links failure.

- _docs/pages/spec.md
Section **Logs** has the same problem on **Data Conventions Guideline** with section **Tags**. add a new RP to fix it.
> fix **Data Conventions Guideline** on Logs section

- _docs/pages/supported-tracers.md
Tweaked css to accommodate the large number of tracers.
New look:
> Added Instana tracers to homepage and docs. 

- _sass/_components/_logo-bar.scss
Tracers and frameworks on certain viewports got a weird render bug that
caused both frameworks and tracers to render on the same row as Tracers.
> fix ios render bug

- _docs/pages/quick-start.md
As of [this PR], July 26, 2016, `HTTPHeaderTextMapCarrier` was renamed
to `HTTPHeadersCarrier`.
[this PR]: https://github.com/opentracing/opentracing-go/pull/102
_____
I was following the quick intro and ran into this. I may propose other small edits in the near future if I run into more.
> pages/quick-start: HTTPHeaderTextMapCarrier -> HTTPHeadersCarrier

- _includes/header.html
I moved it back under the "Github" menu in an effort to keep the landing page (more) uncluttered...
> Adjust contrib link

- _sass/_components/_videos.scss
- _talks_and_videos/2016-09-21-advances-in-cassandra.md
- _talks_and_videos/2016-10-15-an-introduction-to-distributed-tracing-and-zipkin.md
- _talks_and_videos/2017-02-13-ditributed-tracing-and-containers.md
- pages/talks_and_videos.html
local build differed from github pages build because Github has updated their dependencies to use 3.4.3 (https://pages.github.com/versions/) which changed how liquid templates handles the case when a variable is non-existing.
This change resulted in condition `  array | where "featured", ""` not getting fullfilled when `featured` was not set.
Fixed this by adding feature variable to all videos. :)
> Show all videos in the videos section. 

- _docs/pages/instrumentation/common-use-cases.md
@yurishkuro @bhs @wu-sheng Initial stab at the messaging use case.
Someone my need to check the python is valid :)
> Add messaging use case

- pages/outreachy.md
> Outreachy - added initial ideas

- CONTRIBUTING.md
- _docs/pages/instrumentation/instrumenting-frameworks.md
- Fix capitalization of letters after period in CONTRIBUTING.md
- Add missing preposition in between docs of instrumenting-frameworks.md page
> Fix typos and add missing prepositions to pages/documentation

- _includes/hero.html
- _sass/_components/_hero.scss
- _sass/_typography.scss
This is just one option of many... here's how it looks:
Curious what people think. cc @opentracing/otsc since not many people watch this repo.
> Propose a more precise tagline

- LICENSE.md
- README.md
- package.json
(CCing @dankohn who has requested this work)
GitHub uses a library called Licensee to identify a project's license
type. It shows this information in the status bar and via the API if it
can unambiguously identify the license.
This commit replaces the contents of the LICENSE file with the text
of the Apache 2.0 license (Copyright The OpenTracing Authors). It also
updates package.json to refer to the Apache license and slightly
modifies the header in the README. This all allows Licensee's license
type identification (as Apache 2.0) to succeed.
> edit opentracing.io license info so that GitHub recognizes it

- README.md
Since we are about to have a lot of 2.0 activity, it would help if the current readme pointed people to the new site.
> Add 2.0 announcement to README

- content/documentation/api.md
- content/documentation/api/api-implementations.md
- content/documentation/api/cross-process-tracing.md
- content/documentation/api/data-conventions.md
- content/documentation/authors-and-contributors.md
- content/documentation/best-practices.md
- content/documentation/instrumentation/common-use-cases.md
- content/documentation/instrumentation/instrumenting-frameworks.md
- content/documentation/instrumentation/instrumenting-large-systems.md
- content/documentation/instrumentation/practices.md
- content/documentation/quick-start.md
- content/documentation/spec.md
- content/documentation/supported-tracers.md
- content/documentation/translations.md
- data/links.yaml
Copy/paste legacy content into v2.0 framework in preparation for the docathon this week.
I added a few pages that were missing from v2.0, but basically kept the same file names and organization as the v1.0 site.   I think I've got everything, but I'll give it a second pass tomorrow just to make sure.
> Copy/paste legacy content into v2.0 framework.

- README.md
There's a newer release of Hugo that breaks docs installation for me on Mac OS, .42.
I get an error `panic: AllThemes not set`, and the `make` command fails.
As a temporary workaround, adding a note about the proper version, and how to install it on Mac OS with Homebrew.
> Install note about proper Hugo version

- content/guides/python/quickstart.md
This is a WIP, trying to flesh out a Python Quickstart to address issue #305. 
Open to feedback about structure.
For now, the great [Python OpenTracing tutorial](https://github.com/yurishkuro/opentracing-tutorial/tree/master/python) by Yuri seems to have a lot of overlap with what this should be? So for now, I've linked to that, and tried to start from an iPython interactive shell to send off first spans.
Let me know if this makes sense, or if we want to change the Quickstart structure to be substantially different from what I've got here.
Besides this, I'd like to add in some images of the Jaeger web interface if nobody has any problems with that. I could also do other vendors too, if there are stronger feelings.
Happy to hear feedback, and thanks for all the work team!
> Add Content: Python Quickstart

- _data/links.yaml
- pages/outreachy-201702.md
This PR fixes the URL to the second Outreachy program from 2017 and adds an Outreachy option to the Community drop down menu. Here's how it renders now:
> Added link to the Outreachy page and fixed permalink to old progam page

- data/links.yaml
- themes/tracer/layouts/partials/header.html
This adds a new link to the navbar ('Registry') that will currently point to the OT-Contrib meta page. Eventually, this will lead to the OT Registry page itself.
> Add link to the OT-Contrib GitHub Page

- content/get-involved/outreachy/_index.md
- content/get-involved/outreachy/outreachy-201701.md
- content/get-involved/outreachy/outreachy-201801.md
- content/get-involved/outreachy/outreachy-201802.md
- themes/tracer/layouts/get-involved/list.html
- themes/tracer/layouts/get-involved/single.html
- themes/tracer/layouts/partials/header.html
Fixes #344 
I also refactored the menu in get-involved to match the docs/guides one and put the outreachy stuff in a subsection to be consistent with other parts of the site.
> Restore old Outreachy pages that didn't make it over.

- content/registry/brave-tracer-java.md
We discussed and we want to remove individual attribution for our stuff since it is collectively owned and maintained
> Removing specific author attribution

- content/registry/go-tracer-appoptics.md
adds a mention of the OT tracer in https://github.com/appoptics/appoptics-apm-go
> Add AppOptics tracer to the OpenTracing Registry

- themes/tracer/layouts/partials/home/cncf.html
- themes/tracer/layouts/partials/home/hero.html
This adds some dynamic fetching of the Medium RSS feed in order to display the most recent post on the frontpage rather than using the site data supplied URL.
> Featured Medium post should be most recent post

- config.yaml
Since
https://github.com/opentracing-contrib/examples/commit/dd9b3e3c349748805c619c7950938345d240e51e
landed, the go example mentioned in `bashWindowText` produces jaeger.thrift instead
of zipkin.thrift, and consequently hits udp port 6831 instead of udp port 5775.
Not sure if `content/docs/getting-started/_index.md` also needs to change.
> Fix bashWindowText to match change in opentracing-contrib/examples

- content/registry/python-dbapi.md
Includes registry entry for https://github.com/opentracing-contrib/python-dbapi
> Add Python DB API instrumentation

- content/registry/python-requests.md
Includes registry entry for https://github.com/opentracing-contrib/python-requests
> Add Python Requests instrumentation

- content/guides/python/tracers.md
The link for inject-extract on guides/python/tracers was 404'ing.
Link this to the correct path
> Fix broken link on python/tracers

- content/registry/nodetracing.md
---
title: nodetracing
registryType: tracer
tags:
- nodejs
- webui
- docker
- opentracing
repo: https://github.com/cheneyweb/nodetracing
license: Apache License 2.0
description: Automatic instrumentation and tracer of nodejs application, support asyncfunction/http/grpc/axios/express/koa etc.
authors: CheneyXu <457299596@qq.com>
otVersion: latest
---
> Add nodetracing to the registry

- content/registry/dd-trace-dotnet.md
- add supported OpenTracing version
- fix incorrect license
- rename tag for consistency
> update registry entry for Datadog .NET Tracer

- content/registry/java-opentracing-basic.md
Adds reference to the opentracing-basic lib here: https://github.com/eBay/opentracing-basic/
> Add contribution: opentracing-basic lib for java

- content/registry/java-aws-xray.md
We've written a thin wrapper to implement the OpenTracing API around the AWS X-Ray SDK. I'd like to add this to the registry since there doesn't seem to be an implementation yet, and I think this would be useful to the broader OpenTracing community.
> Add opentracing-java-aws-xray to registry

- themes/tracer/assets/scss/_components/_logo-bar.scss
Due to the dimensions of the Elastic logo, it is being
scaled in such a way as to look awkward and out of place
in the carousel. Tweak its height and max-height slightly.
Before:
After:
> Add some height to the Elastic logo

- content/guides/java/_index.md
Fix a simple typo in the comments and unindent the code so it lines up properly on the left.
> Fix typo and indentation in Opentracing Java documentation 

- content/docs/overview/spans.md
- content/docs/overview/tags-logs-baggage.md
And apparently removes trailing spaces from the Markdown.  :)
> Fix database spelling

- content/docs/overview/spans.md
Changed db.instance to use table name as specified in https://github.com/opentracing/specification/blob/master/semantic_conventions.md and added peer.address to keep the example similar to before (excluding the jdbc prefix as specified in the semantic conventions)
> Fixed example span tags

- content/guides/golang/quick-start.md
Ran into this when setting up a test-case for myself.
```
internal/trace/trace_test.go:24:7: child.finish undefined (type opentracing.Span has no field or method finish, but does have Finish)
```
> guides/golang: fix quick-start compile error

- content/registry/go-opentracing-go-redis
I searched for the redis client of golang with opentracing, they are all out of date. 
I noticed there was an instrumentation of go-redis (https://github.com/opentracing-contrib/goredis) supports the v6 version of go-redis. 
While the latest version is v8 and they have changed their "WrapProcess" method to "Hook" interface.
Also I noticed go-redis has their own tracing based on OpenTelemetry (https://redis.uptrace.dev/tracing/).
So I just modified it to support opentracing.
Here it is.
> instrumentation of newest go-redis

- content/registry/go-opentracing-redis-v8.md
[registry](https://opentracing.io/registry/) does not have a instrumentation that supports [go-redis](https://github.com/go-redis/redis), so I want to add it.
> Add go-redis-v8 instrumentation

- content/docs/faq.md
`Join OpenTracing Contrib` link was broken by #346
> Remove invalid contrib link from FAQ
